"""ocr_raw_text now a required field

Revision ID: b941779ff276
Revises: 08f3a7ed3dbe
Create Date: 2026-06-16 14:34:47.202008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b941779ff276'
down_revision: Union[str, Sequence[str], None] = '08f3a7ed3dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pill_bottle', 'ocr_raw_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pill_bottle', 'ocr_raw_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
