"""create pill_bottle and device_usage tables

Revision ID: b305a66eee07
Revises: 
Create Date: 2026-06-07 10:53:09.620360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b305a66eee07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_usage',
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.Column('hourly_user_usage', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_fingerprint')
    )
    op.create_table('pill_bottle',
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pill_bottle')
    op.drop_table('device_usage')
    # ### end Alembic commands ###
