"""soft delete mixin added to Bottle API

Revision ID: 08f3a7ed3dbe
Revises: b305a66eee07
Create Date: 2026-06-16 11:46:12.536095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f3a7ed3dbe'
down_revision: Union[str, Sequence[str], None] = 'b305a66eee07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pill_bottle', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pill_bottle', 'deleted_at')
    # ### end Alembic commands ###
